### ISSUE TITLE
Change app id in manifest.xml

### ISSUE THREAD

**Issue by kopa** [roelofk/HeartRateRunner#1]
Please change application id in manifest.xml as our apps replace each other on installation - maybe even in the app store...

Otherwise your additions looks great! Thanks for giving credits to me!

Br Konrad

**Comment by roelofk** [comment]
Oh! 

Sorry about that, I noticed that and fixed it in version 1.0.3.

Can you please try with that version if it does not work, please let me know.

Thank you and again thank you for sharing your work.

Roelof

**Comment by kopa** [comment]
Oh, seems your code here on github was behind release version.
git push to the rescue ;-)

**Comment by roelofk** [comment]
OK that explains a lot can you please dry and reloaded from the App Store because I want to know if it works from there thank you

Roelof

**Comment by kopa** [comment]
fixed version in app.store.
would you mind updating the github sources? just curious ;-)

**Comment by roelofk** [comment]
I will do that this evening I am currently on my commute home so that will take an hour or so. 

Roelof

**Comment by roelofk** [comment]
Hi Konrad,

I have checked in my latest version on Github.

I have made some changes because in my training I’m focusing on heart rate and time spend in heart zones. Because of memory issues I had to leave out the battery and gps visualizations.
I have put back the gps signal but only in text (poor, weak, ok, strong).

By the way if you like it could you leave a review on the store, because someone putting in chinese characters has put in a 1 star review (looks like spam).

Thank you!
